name: Create new issue
description: File a bug report.
labels: bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What are the steps you took that hit this issue?
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Are there any recent changes that introduced the issue?
      description: If so, what are those changes?
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment did you use? You may select more than one.
      multiple: true
      options:
        - Dev
        - QA
        - Prod
    validations:
      required: true
